# configuration
SECRET_KEY = 'development key'
COUCHDB_SERVER = 'http://127.0.0.1:5984'
COUCHDB_DATABASE = 'db_bs'
SESSION_COOKIE_NAME = 'bizCards'
SESSION_COOKIE_SECURE = True
PERMANENT_SESSION_LIFETIME = 600
SESSION_TYPE = 'filesystem'
SESSION_USE_SIGNER = True